// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvclab2.Models;

#nullable disable

namespace mvclab2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230803075429_addtables")]
    partial class addtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mvc2.Models.Emp_Project", b =>
                {
                    b.Property<int>("Emp_id")
                        .HasColumnType("int");

                    b.Property<int>("Project_id")
                        .HasColumnType("int");

                    b.Property<int>("Working_hours")
                        .HasColumnType("int");

                    b.Property<int?>("employeesId")
                        .HasColumnType("int");

                    b.Property<int?>("projectsId")
                        .HasColumnType("int");

                    b.HasKey("Emp_id", "Project_id");

                    b.HasIndex("employeesId");

                    b.HasIndex("projectsId");

                    b.ToTable("emp_Projects");
                });

            modelBuilder.Entity("mvc2.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("mvc2.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("offices");
                });

            modelBuilder.Entity("mvc2.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("mvc2.Models.Emp_Project", b =>
                {
                    b.HasOne("mvc2.Models.Employee", "employees")
                        .WithMany("emp_projects")
                        .HasForeignKey("employeesId");

                    b.HasOne("mvc2.Models.Project", "projects")
                        .WithMany("emp_projects")
                        .HasForeignKey("projectsId");

                    b.Navigation("employees");

                    b.Navigation("projects");
                });

            modelBuilder.Entity("mvc2.Models.Employee", b =>
                {
                    b.HasOne("mvc2.Models.Office", "office")
                        .WithMany("employees")
                        .HasForeignKey("OfficeId");

                    b.Navigation("office");
                });

            modelBuilder.Entity("mvc2.Models.Employee", b =>
                {
                    b.Navigation("emp_projects");
                });

            modelBuilder.Entity("mvc2.Models.Office", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("mvc2.Models.Project", b =>
                {
                    b.Navigation("emp_projects");
                });
#pragma warning restore 612, 618
        }
    }
}
